import type { StudentWork, ConversationOutput } from './types'
import { getClient } from './llm-client'
import { createAdminClient } from './supabase-admin'
import { scoreVoiceFidelity } from './voice-fidelity'
import {
  PHASE_1_SYSTEM_PROMPT,
  PHASE_2_SYSTEM_PROMPT,
  PHASE_3_SYSTEM_PROMPT,
  SYNTHESIS_SYSTEM_PROMPT,
  SKILL_TAG_SYSTEM_PROMPT,
  WORK_SKILL_TAG_SYSTEM_PROMPT,
  CONVERSATION_OUTPUT_SYSTEM_PROMPT,
  NARRATIVE_GENERATION_SYSTEM_PROMPT,
  CAREER_OUTPUT_SYSTEM_PROMPT,
  buildPhase1Context,
  buildPhase2Context,
  buildPhase3Context,
  buildSynthesisContext,
  buildSkillTagContext,
  buildWorkSkillTagContext,
  buildReflectionPhase1Context,
  buildConversationOutputContext,
  buildNarrativeContext,
  buildCareerOutputContext,
  type ConversationContext,
  type NarrativeContext,
} from './llm-prompts'

// All functions use the default LLM client (set via LLM_PROVIDER env var)
const llm = () => getClient()

/**
 * Parse JSON from an LLM response. Claude and other models frequently
 * wrap structured output in ```json ... ``` fences despite instructions
 * not to, so we strip common fence patterns before parsing. Falls back
 * to the supplied default if parsing still fails.
 *
 * Order of attempts:
 *   1. Raw parse (happy path when the model actually obeys the prompt)
 *   2. Strip surrounding markdown code fences, parse again
 *   3. Extract the first balanced {} or [] block in the string, parse
 *   4. Return the fallback
 */
function parseJsonFromLLM<T>(text: string, fallback: T): T {
  if (!text) return fallback

  // 1. Happy path
  try {
    return JSON.parse(text) as T
  } catch {
    /* fall through */
  }

  // 2. Strip markdown code fences
  const stripped = text
    .trim()
    .replace(/^```(?:json)?\s*\n?/i, '')
    .replace(/\n?\s*```\s*$/i, '')
    .trim()
  if (stripped !== text.trim()) {
    try {
      return JSON.parse(stripped) as T
    } catch {
      /* fall through */
    }
  }

  // 3. Extract the first {...} or [...] block. This is naive but
  // sufficient for the LLM outputs we actually see.
  const blockMatch = text.match(/([{\[][\s\S]*[}\]])/)
  if (blockMatch) {
    try {
      return JSON.parse(blockMatch[1]) as T
    } catch {
      /* fall through */
    }
  }

  return fallback
}

export async function generatePhase1Question(context: ConversationContext): Promise<string> {
  return llm().generate(PHASE_1_SYSTEM_PROMPT, buildPhase1Context(context))
}

export async function generatePhase2Question(
  context: ConversationContext,
  phase1Response: string
): Promise<string> {
  return llm().generate(PHASE_2_SYSTEM_PROMPT, buildPhase2Context(context, phase1Response))
}

export async function generatePhase3Question(
  context: ConversationContext,
  phase1Response: string,
  phase2Response: string
): Promise<string> {
  return llm().generate(PHASE_3_SYSTEM_PROMPT, buildPhase3Context(context, phase1Response, phase2Response))
}

export async function generateSynthesis(
  context: ConversationContext,
  phases: { p1: string; p2: string; p3: string }
): Promise<{ synthesisText: string; suggestedInsight: string }> {
  const text = await llm().generate(
    SYNTHESIS_SYSTEM_PROMPT,
    buildSynthesisContext(context, phases),
    { temperature: 0.3, maxTokens: 300 }
  )
  return parseJsonFromLLM(text, {
    synthesisText: text,
    suggestedInsight: 'Pattern: unable to parse structured insight',
  })
}

export async function suggestSkillTags(
  context: ConversationContext,
  phases: { p1: string; p2: string; p3: string },
  synthesis: string
): Promise<{ skillId: string; confidence: number; rationale: string }[]> {
  const text = await llm().generate(
    SKILL_TAG_SYSTEM_PROMPT,
    buildSkillTagContext(context, phases, synthesis),
    { temperature: 0.2, maxTokens: 500 }
  )
  const raw = parseJsonFromLLM<{ skillId: string; confidence: number; rationale: string }[]>(text, [])
  return resolveSkillIds(raw)
}

export async function autoTagWork(
  work: StudentWork,
  coverageCounts?: Record<string, number>
): Promise<{ skillId: string; confidence: number; rationale: string }[]> {
  const text = await llm().generate(
    WORK_SKILL_TAG_SYSTEM_PROMPT,
    buildWorkSkillTagContext(work, coverageCounts),
    { temperature: 0.2, maxTokens: 500 }
  )
  const raw = parseJsonFromLLM<{ skillId: string; confidence: number; rationale: string }[]>(text, [])
  return resolveSkillIds(raw)
}

/**
 * Skill ID resolution cache.
 *
 * The LLM returns human-readable identifiers like "skill_critical_thinking"
 * (because that's what the prompt tells it to use). The database stores real
 * UUIDs generated by str_to_uuid() during seeding. This cache maps the
 * LLM-style identifiers back to real UUIDs so auto-tagger inserts don't
 * fail on FK mismatch.
 *
 * Built lazily on first use and cached in-process. The map includes both
 * the exact string identifier format ("skill_critical_thinking") and the
 * lowercased skill name ("critical thinking") so we can match regardless
 * of what the LLM decides to return.
 */
let skillIdCache: Map<string, string> | null = null

async function getSkillIdMap(): Promise<Map<string, string>> {
  if (skillIdCache) return skillIdCache

  const admin = createAdminClient()
  const { data: skills } = await admin
    .from('durable_skill')
    .select('id, name')
    .eq('is_active', true)

  const map = new Map<string, string>()
  for (const skill of skills || []) {
    const uuid = skill.id as string
    const name = skill.name as string

    // Map the UUID to itself (in case the LLM returns a UUID directly)
    map.set(uuid, uuid)

    // Map the lowercased skill name: "Critical Thinking" → uuid
    map.set(name.toLowerCase(), uuid)

    // Map the underscore identifier: "skill_critical_thinking" → uuid
    const identifier = 'skill_' + name.toLowerCase().replace(/[^a-z0-9]+/g, '_')
    map.set(identifier, uuid)

    // Map without the "skill_" prefix too: "critical_thinking" → uuid
    map.set(identifier.replace(/^skill_/, ''), uuid)
  }

  skillIdCache = map
  return map
}

/**
 * Resolve LLM-returned skill identifiers to real database UUIDs.
 * Drops any tags that can't be resolved (unknown skill names).
 */
async function resolveSkillIds(
  tags: { skillId: string; confidence: number; rationale: string }[]
): Promise<{ skillId: string; confidence: number; rationale: string }[]> {
  if (tags.length === 0) return tags

  const map = await getSkillIdMap()
  const resolved: { skillId: string; confidence: number; rationale: string }[] = []

  for (const tag of tags) {
    // Try exact match first, then lowercased
    const uuid = map.get(tag.skillId) || map.get(tag.skillId.toLowerCase())
    if (uuid) {
      resolved.push({ ...tag, skillId: uuid })
    } else {
      console.warn(
        `[auto-tagger] Unknown skill identifier "${tag.skillId}" — dropping tag. ` +
        `Known identifiers: ${Array.from(map.keys()).slice(0, 10).join(', ')}...`
      )
    }
  }

  return resolved
}

export async function generateConversationOutput(
  conversation: { promptPhase1?: string; responsePhase1?: string; promptPhase2?: string; responsePhase2?: string; promptPhase3?: string; responsePhase3?: string; synthesisText?: string },
  skillTags: { skillId: string }[],
  rubricDescriptors: Record<string, Record<string, string[]>>,
  previousConversations?: { synthesisText?: string; suggestedInsight?: string }[]
): Promise<Omit<ConversationOutput, 'id' | 'conversationId' | 'createdAt'>> {
  const text = await llm().generate(
    CONVERSATION_OUTPUT_SYSTEM_PROMPT,
    buildConversationOutputContext(conversation, skillTags, rubricDescriptors, previousConversations),
    { temperature: 0.2, maxTokens: 1500 }
  )
  return parseJsonFromLLM<Omit<ConversationOutput, 'id' | 'conversationId' | 'createdAt'>>(text, {
    evidenceStrength: 'thin',
    evidenceRationale: 'Failed to parse structured output',
    behavioralIndicators: [],
    sdtLevelSignals: {},
    growthTrajectory: 'emerging',
    trajectoryRationale: 'Unable to assess',
    keyMoments: [],
    voiceMarkers: {
      sentenceLength: 'medium',
      vocabulary: 'conversational',
      metaphors: [],
      repeatPhrases: [],
      emotionalRegister: 'neutral',
    },
  })
}

export async function generateCareerOutput(
  studentName: string,
  narratives: {
    skillName: string
    skillId: string
    narrativeText: string
    /**
     * Per-narrative citations carried forward from skill_narrative.
     * Threaded into the prompt so the career LLM can annotate its
     * resume sentences and talking points with the same conversationIds.
     */
    citations?: Array<{ sentence: string; conversationId: string }>
  }[]
): Promise<{
  resumeSummary: string
  skillDescriptions: {
    skillId: string
    skillName: string
    resumeLanguage: string
    talkingPoints: string[]
    /**
     * Sentence→conversationId map for inline source links on the v2
     * career view. Each entry's `sentence` is a verbatim slice of either
     * resumeLanguage or one of the talkingPoints for the same skill.
     * Scoped per-skill — cross-skill annotations are dropped.
     */
    annotations: Array<{ sentence: string; conversationId: string }>
  }[]
}> {
  const text = await llm().generate(
    CAREER_OUTPUT_SYSTEM_PROMPT,
    buildCareerOutputContext(studentName, narratives),
    { temperature: 0.4, maxTokens: 2000 }
  )
  const parsed = parseJsonFromLLM<{
    resumeSummary: string
    skillDescriptions: Array<{
      skillId: string
      skillName: string
      resumeLanguage: string
      talkingPoints: string[]
      annotations?: Array<{ sentence: string; conversationId: string }>
    }>
  }>(text, { resumeSummary: text, skillDescriptions: [] })

  // Build the per-skill set of valid conversationIds (the ones we passed
  // INTO the prompt) so we can drop hallucinated ids the model might emit.
  const allowedConvoIdsBySkill = new Map<string, Set<string>>()
  for (const n of narratives) {
    allowedConvoIdsBySkill.set(
      n.skillId,
      new Set((n.citations ?? []).map(c => c.conversationId))
    )
  }

  // Validate each skill's annotations: sentence must appear verbatim in
  // resumeLanguage or one of the talkingPoints for THAT skill, and the
  // conversationId must be one of the citations we passed in for that
  // same skill. Anything else gets silently dropped — the UI's nullish
  // fallback handles a missing/empty annotations list cleanly.
  const skillDescriptions = parsed.skillDescriptions.map(sd => {
    const allowedHaystack = [sd.resumeLanguage, ...(sd.talkingPoints ?? [])]
      .filter(Boolean)
      .join('\n')
    const allowedIds = allowedConvoIdsBySkill.get(sd.skillId) ?? new Set<string>()
    const validAnnotations = (sd.annotations ?? []).filter(
      a =>
        typeof a.sentence === 'string' &&
        typeof a.conversationId === 'string' &&
        a.sentence.length > 0 &&
        allowedIds.has(a.conversationId) &&
        allowedHaystack.includes(a.sentence)
    )
    return {
      skillId: sd.skillId,
      skillName: sd.skillName,
      resumeLanguage: sd.resumeLanguage,
      talkingPoints: sd.talkingPoints ?? [],
      annotations: validAnnotations,
    }
  })

  return {
    resumeSummary: parsed.resumeSummary,
    skillDescriptions,
  }
}

export async function generateSkillNarrative(
  ctx: NarrativeContext
): Promise<{
  narrativeText: string
  richness: 'thin' | 'developing' | 'rich'
  /**
   * Sentence → conversationId map emitted alongside narrativeText. Each
   * entry's `sentence` is a verbatim slice of narrativeText; the renderer
   * locates it via substring match to render an inline source link. May
   * be empty if the model produced no groundable sentences, or if the
   * surface couldn't parse it cleanly.
   */
  citations: Array<{ sentence: string; conversationId: string }>
  voiceFidelity: { groundedPhraseCount: number; coverage: number; passed: boolean; groundedPhrases: string[] }
}> {
  // The student's own words, assembled for the fidelity check.
  const studentCorpus = [
    ...ctx.conversations.map(c => c.responseText).filter(Boolean),
    ...ctx.definitions.map(d => d.text),
  ].join(' ')

  type NarrativeJson = {
    narrativeText: string
    richness: 'thin' | 'developing' | 'rich'
    citations?: Array<{ sentence: string; conversationId: string }>
  }
  const userPrompt = buildNarrativeContext(ctx)

  const genOnce = async (extra: string): Promise<NarrativeJson> => {
    const raw = await llm().generate(
      NARRATIVE_GENERATION_SYSTEM_PROMPT,
      userPrompt + extra,
      { temperature: 0.5, maxTokens: 2000 }
    )
    return parseJsonFromLLM<NarrativeJson>(raw, { narrativeText: raw, richness: 'thin', citations: [] })
  }

  let parsed = await genOnce('')
  let fidelity = scoreVoiceFidelity(parsed.narrativeText, studentCorpus, parsed.richness)
  // Only retry when there's a corpus to ground against — an empty corpus
  // (no student prose, no definitions) can never raise the score, so a
  // second generation would be pure waste on this hot path.
  if (studentCorpus.trim() && !fidelity.passed) {
    // Degrade, never block: try once more with a stronger nudge. A weaker
    // narrative still ships.
    const retry = await genOnce(
      '\n\nREVISION: Use MORE of the student\'s own words verbatim — anchor each ' +
        'paragraph in a specific moment they described. Remove any "not X — it\'s Y" ' +
        'construction. Return the same JSON shape.'
    )
    const retryFidelity = scoreVoiceFidelity(retry.narrativeText, studentCorpus, retry.richness)
    // Prefer an attempt that PASSES — the retry's job is often to clear a
    // banned AI-ism, which flips `passed` without necessarily raising the
    // phrase count. Only when both share the same passed-state do we keep
    // whichever grounded more of the student's words.
    const retryIsBetter =
      (retryFidelity.passed && !fidelity.passed) ||
      (retryFidelity.passed === fidelity.passed &&
        retryFidelity.groundedPhraseCount >= fidelity.groundedPhraseCount)
    if (retryIsBetter) {
      parsed = retry
      fidelity = retryFidelity
    }
  }

  // Validate every citation: sentence must be findable in narrativeText AND
  // conversationId must be one we provided in the context. Drop any that
  // fail either check — the model occasionally paraphrases or hallucinates
  // a uuid, and bad annotations would render as broken inline links.
  const allowedConvoIds = new Set(ctx.conversations.map(c => c.conversationId))
  const validCitations = (parsed.citations ?? []).filter(
    c =>
      typeof c.sentence === 'string' &&
      typeof c.conversationId === 'string' &&
      c.sentence.length > 0 &&
      allowedConvoIds.has(c.conversationId) &&
      parsed.narrativeText.includes(c.sentence)
  )

  return {
    narrativeText: parsed.narrativeText,
    richness: parsed.richness,
    citations: validCitations,
    voiceFidelity: {
      groundedPhraseCount: fidelity.groundedPhraseCount,
      coverage: fidelity.coverage,
      passed: fidelity.passed,
      groundedPhrases: fidelity.groundedPhrases,
    },
  }
}

export async function generateReflectionPhase1Question(
  context: ConversationContext,
  reflectionDescription: string,
  taggedSkillName: string
): Promise<string> {
  return llm().generate(
    PHASE_1_SYSTEM_PROMPT,
    buildReflectionPhase1Context(context, reflectionDescription, taggedSkillName)
  )
}
