import type { StudentWork, ConversationOutput } from './types'
import { getClient } from './llm-client'
import { createAdminClient } from './supabase-admin'
import {
  PHASE_1_SYSTEM_PROMPT,
  PHASE_2_SYSTEM_PROMPT,
  PHASE_3_SYSTEM_PROMPT,
  SYNTHESIS_SYSTEM_PROMPT,
  SKILL_TAG_SYSTEM_PROMPT,
  WORK_SKILL_TAG_SYSTEM_PROMPT,
  CONVERSATION_OUTPUT_SYSTEM_PROMPT,
  NARRATIVE_GENERATION_SYSTEM_PROMPT,
  CAREER_OUTPUT_SYSTEM_PROMPT,
  buildPhase1Context,
  buildPhase2Context,
  buildPhase3Context,
  buildSynthesisContext,
  buildSkillTagContext,
  buildWorkSkillTagContext,
  buildReflectionPhase1Context,
  buildConversationOutputContext,
  buildNarrativeContext,
  buildCareerOutputContext,
  type ConversationContext,
  type NarrativeContext,
} from './llm-prompts'

// All functions use the default LLM client (set via LLM_PROVIDER env var)
const llm = () => getClient()

/**
 * Parse JSON from an LLM response. Claude and other models frequently
 * wrap structured output in ```json ... ``` fences despite instructions
 * not to, so we strip common fence patterns before parsing. Falls back
 * to the supplied default if parsing still fails.
 *
 * Order of attempts:
 *   1. Raw parse (happy path when the model actually obeys the prompt)
 *   2. Strip surrounding markdown code fences, parse again
 *   3. Extract the first balanced {} or [] block in the string, parse
 *   4. Return the fallback
 */
function parseJsonFromLLM<T>(text: string, fallback: T): T {
  if (!text) return fallback

  // 1. Happy path
  try {
    return JSON.parse(text) as T
  } catch {
    /* fall through */
  }

  // 2. Strip markdown code fences
  const stripped = text
    .trim()
    .replace(/^```(?:json)?\s*\n?/i, '')
    .replace(/\n?\s*```\s*$/i, '')
    .trim()
  if (stripped !== text.trim()) {
    try {
      return JSON.parse(stripped) as T
    } catch {
      /* fall through */
    }
  }

  // 3. Extract the first {...} or [...] block. This is naive but
  // sufficient for the LLM outputs we actually see.
  const blockMatch = text.match(/([{\[][\s\S]*[}\]])/)
  if (blockMatch) {
    try {
      return JSON.parse(blockMatch[1]) as T
    } catch {
      /* fall through */
    }
  }

  return fallback
}

export async function generatePhase1Question(context: ConversationContext): Promise<string> {
  return llm().generate(PHASE_1_SYSTEM_PROMPT, buildPhase1Context(context))
}

export async function generatePhase2Question(
  context: ConversationContext,
  phase1Response: string
): Promise<string> {
  return llm().generate(PHASE_2_SYSTEM_PROMPT, buildPhase2Context(context, phase1Response))
}

export async function generatePhase3Question(
  context: ConversationContext,
  phase1Response: string,
  phase2Response: string
): Promise<string> {
  return llm().generate(PHASE_3_SYSTEM_PROMPT, buildPhase3Context(context, phase1Response, phase2Response))
}

export async function generateSynthesis(
  context: ConversationContext,
  phases: { p1: string; p2: string; p3: string }
): Promise<{ synthesisText: string; suggestedInsight: string }> {
  const text = await llm().generate(
    SYNTHESIS_SYSTEM_PROMPT,
    buildSynthesisContext(context, phases),
    { temperature: 0.3, maxTokens: 300 }
  )
  return parseJsonFromLLM(text, {
    synthesisText: text,
    suggestedInsight: 'Pattern: unable to parse structured insight',
  })
}

export async function suggestSkillTags(
  context: ConversationContext,
  phases: { p1: string; p2: string; p3: string },
  synthesis: string
): Promise<{ skillId: string; confidence: number; rationale: string }[]> {
  const text = await llm().generate(
    SKILL_TAG_SYSTEM_PROMPT,
    buildSkillTagContext(context, phases, synthesis),
    { temperature: 0.2, maxTokens: 500 }
  )
  const raw = parseJsonFromLLM<{ skillId: string; confidence: number; rationale: string }[]>(text, [])
  return resolveSkillIds(raw)
}

export async function autoTagWork(
  work: StudentWork,
  coverageCounts?: Record<string, number>
): Promise<{ skillId: string; confidence: number; rationale: string }[]> {
  const text = await llm().generate(
    WORK_SKILL_TAG_SYSTEM_PROMPT,
    buildWorkSkillTagContext(work, coverageCounts),
    { temperature: 0.2, maxTokens: 500 }
  )
  const raw = parseJsonFromLLM<{ skillId: string; confidence: number; rationale: string }[]>(text, [])
  return resolveSkillIds(raw)
}

/**
 * Skill ID resolution cache.
 *
 * The LLM returns human-readable identifiers like "skill_critical_thinking"
 * (because that's what the prompt tells it to use). The database stores real
 * UUIDs generated by str_to_uuid() during seeding. This cache maps the
 * LLM-style identifiers back to real UUIDs so auto-tagger inserts don't
 * fail on FK mismatch.
 *
 * Built lazily on first use and cached in-process. The map includes both
 * the exact string identifier format ("skill_critical_thinking") and the
 * lowercased skill name ("critical thinking") so we can match regardless
 * of what the LLM decides to return.
 */
let skillIdCache: Map<string, string> | null = null

async function getSkillIdMap(): Promise<Map<string, string>> {
  if (skillIdCache) return skillIdCache

  const admin = createAdminClient()
  const { data: skills } = await admin
    .from('durable_skill')
    .select('id, name')
    .eq('is_active', true)

  const map = new Map<string, string>()
  for (const skill of skills || []) {
    const uuid = skill.id as string
    const name = skill.name as string

    // Map the UUID to itself (in case the LLM returns a UUID directly)
    map.set(uuid, uuid)

    // Map the lowercased skill name: "Critical Thinking" → uuid
    map.set(name.toLowerCase(), uuid)

    // Map the underscore identifier: "skill_critical_thinking" → uuid
    const identifier = 'skill_' + name.toLowerCase().replace(/[^a-z0-9]+/g, '_')
    map.set(identifier, uuid)

    // Map without the "skill_" prefix too: "critical_thinking" → uuid
    map.set(identifier.replace(/^skill_/, ''), uuid)
  }

  skillIdCache = map
  return map
}

/**
 * Resolve LLM-returned skill identifiers to real database UUIDs.
 * Drops any tags that can't be resolved (unknown skill names).
 */
async function resolveSkillIds(
  tags: { skillId: string; confidence: number; rationale: string }[]
): Promise<{ skillId: string; confidence: number; rationale: string }[]> {
  if (tags.length === 0) return tags

  const map = await getSkillIdMap()
  const resolved: { skillId: string; confidence: number; rationale: string }[] = []

  for (const tag of tags) {
    // Try exact match first, then lowercased
    const uuid = map.get(tag.skillId) || map.get(tag.skillId.toLowerCase())
    if (uuid) {
      resolved.push({ ...tag, skillId: uuid })
    } else {
      console.warn(
        `[auto-tagger] Unknown skill identifier "${tag.skillId}" — dropping tag. ` +
        `Known identifiers: ${Array.from(map.keys()).slice(0, 10).join(', ')}...`
      )
    }
  }

  return resolved
}

export async function generateConversationOutput(
  conversation: { promptPhase1?: string; responsePhase1?: string; promptPhase2?: string; responsePhase2?: string; promptPhase3?: string; responsePhase3?: string; synthesisText?: string },
  skillTags: { skillId: string }[],
  rubricDescriptors: Record<string, Record<string, string[]>>,
  previousConversations?: { synthesisText?: string; suggestedInsight?: string }[]
): Promise<Omit<ConversationOutput, 'id' | 'conversationId' | 'createdAt'>> {
  const text = await llm().generate(
    CONVERSATION_OUTPUT_SYSTEM_PROMPT,
    buildConversationOutputContext(conversation, skillTags, rubricDescriptors, previousConversations),
    { temperature: 0.2, maxTokens: 1500 }
  )
  return parseJsonFromLLM<Omit<ConversationOutput, 'id' | 'conversationId' | 'createdAt'>>(text, {
    evidenceStrength: 'thin',
    evidenceRationale: 'Failed to parse structured output',
    behavioralIndicators: [],
    sdtLevelSignals: {},
    growthTrajectory: 'emerging',
    trajectoryRationale: 'Unable to assess',
    keyMoments: [],
    voiceMarkers: {
      sentenceLength: 'medium',
      vocabulary: 'conversational',
      metaphors: [],
      repeatPhrases: [],
      emotionalRegister: 'neutral',
    },
  })
}

export async function generateCareerOutput(
  studentName: string,
  narratives: { skillName: string; skillId: string; narrativeText: string }[]
): Promise<{ resumeSummary: string; skillDescriptions: { skillId: string; skillName: string; resumeLanguage: string; talkingPoints: string[] }[] }> {
  const text = await llm().generate(
    CAREER_OUTPUT_SYSTEM_PROMPT,
    buildCareerOutputContext(studentName, narratives),
    { temperature: 0.4, maxTokens: 2000 }
  )
  return parseJsonFromLLM<{ resumeSummary: string; skillDescriptions: { skillId: string; skillName: string; resumeLanguage: string; talkingPoints: string[] }[] }>(
    text,
    { resumeSummary: text, skillDescriptions: [] }
  )
}

export async function generateSkillNarrative(
  ctx: NarrativeContext
): Promise<{ narrativeText: string; richness: 'thin' | 'developing' | 'rich' }> {
  const text = await llm().generate(
    NARRATIVE_GENERATION_SYSTEM_PROMPT,
    buildNarrativeContext(ctx),
    { temperature: 0.5, maxTokens: 2000 }
  )
  return parseJsonFromLLM<{ narrativeText: string; richness: 'thin' | 'developing' | 'rich' }>(
    text,
    { narrativeText: text, richness: 'thin' }
  )
}

export async function generateReflectionPhase1Question(
  context: ConversationContext,
  reflectionDescription: string,
  taggedSkillName: string
): Promise<string> {
  return llm().generate(
    PHASE_1_SYSTEM_PROMPT,
    buildReflectionPhase1Context(context, reflectionDescription, taggedSkillName)
  )
}
