/**
 * The data-handling notice body — single source of truth for what we
 * pull from Brightspace, what we don't do, and the AI explanation.
 * Presentational only: no heading, no fetch, no action. Consumers
 * (the first-visit DataConsentModal; the /v2/me review modal) supply
 * their own framing + actions around it.
 */
export function DataHandlingNotice() {
  return (
    <>
      <p className="text-sm text-gray-700 mb-3">
        Here&rsquo;s what we want you to know about how this works.
      </p>

      <h3 className="text-sm font-semibold text-gray-900 mt-4 mb-2">
        What we bring in from Brightspace
      </h3>
      <p className="text-sm text-gray-700 mb-2">
        To help you reflect on your actual work, we automatically pull a few
        things from your LE3 courses on D2L Brightspace:
      </p>
      <ul className="text-sm text-gray-700 list-disc pl-5 space-y-1 mb-3">
        <li>
          Your enrollment in LE3 courses (the course names you&rsquo;re
          taking)
        </li>
        <li>
          Assignments your instructors have set up — title, instructions,
          and due date
        </li>
        <li>
          Files you&rsquo;ve submitted to those assignments. We extract
          text from those files so we can reference them in conversations
          with you.
        </li>
        <li>
          Grades and feedback your instructors provided on those
          submissions
        </li>
        <li>Your name and email (the same ones D2L has)</li>
      </ul>

      <h3 className="text-sm font-semibold text-gray-900 mt-4 mb-2">
        What we don’t do
      </h3>
      <ul className="text-sm text-gray-700 list-disc pl-5 space-y-1 mb-3">
        <li>We don&rsquo;t share your reflections with other students</li>
        <li>
          We don&rsquo;t send your work to instructors — only your assigned
          LE3 coach sees what you write here
        </li>
        <li>We don&rsquo;t use your work to train external AI models</li>
      </ul>

      <h3 className="text-sm font-semibold text-gray-900 mt-4 mb-2">
        AI in the conversations
      </h3>
      <p className="text-sm text-gray-700 mb-3">
        The reflective questions you&rsquo;ll see are generated by an AI
        model that reads your submitted work and your previous responses.
        It does not replace your coach — it helps you think out loud
        before you meet with them.
      </p>

      <p className="text-[11px] text-gray-400 mt-3 text-center">
        Questions about your data? Reach out to your LE3 coach.
      </p>
    </>
  )
}
